name: python-linting-checker
run-name: ${{ github.run_id }}, update authored by @${{ github.actor }}
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install ruff==0.1.15
      - run: ruff --respect-gitignore $GITHUB_WORKSPACE # ruff automatically finds python files
