name: 'Secret Scan'
description: 'Run Secret Scanning tools acrosss a repository to ensure that the repo is not compromised'
inputs:
  scan-path:  
    description: 'path to scan for secrets'
    required: true
    default: '${{ github.workspace }}'
outputs:
  verified-secrets:
    description: "Number of verified secrets found"
    value: ${{ steps.secrets-found.outputs.verified-secrets }}
  unverified-secrets:
    description: "Number of verified secrets found"
    value: ${{ steps.secrets-found.outputs.unverified-secrets }}
runs:
  using: composite
  steps:
    - run: |
        ls -lah ${{github.workspace}} && \
        docker run -t -v "${{inputs.scan-path}}:/workdir" trufflesecurity/trufflehog:latest filesystem /workdir \
        --fail --only-verified --json --debug | tee docker.out
        cat docker.out
        jq -cs '.[-1]|{"verified":.verified_secrets, "unverified":.unverified_secrets}' docker.out \
        | tee /tmp/th.out
        cat /tmp/th.out
      shell: bash
    - id: secrets-found
      run: |
        echo "verified-secrets=$(jq '."verified"' /tmp/th.out)" >> $GITHUB_OUTPUT && \
        echo "unverified-secrets=$(jq '."unverified"' /tmp/th.out)" >> $GITHUB_OUTPUT
      shell: bash
 