name: test-secret-scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout test data
      uses: actions/checkout@v4
      with:
        repository: trufflesecurity/test_keys
        path: test_keys
    - name: Scan Test Data
      uses: ./secret-scan
      with:
        scan-path: ${{ github.workspace }}/test_keys
    - name: Fail if not found
      if: steps.scan.outputs.verified-secrets != 2
      uses: actions/github-script@v6
      with:
        script: |
            core.setFailed('Incorrect number of secrets found.')
