name: test-secret-scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout Test Data
      uses: actions/checkout@v4
      with:
        repository: trufflesecurity/test_keys
        path: test_keys
        clean: false
    - name: debug info
      run: |
        echo $PWD
        ls -lah
    - name: Scan Test Data
      id: scan
      uses: ./secret-scan
      with:
        scan-path: ${{ github.workspace }}/test_keys
    - name: Log Outputs
      uses: actions/github-script@v6
      with:
        script: |
            core.info(`Number of verified secrets: ${{steps.scan.outputs.verified-secrets}}`)
            core.info(`Number of unverified secrets: ${{steps.scan.outputs.unverified-secrets}}`)
    - name: Fail if not found
      if: steps.scan.outputs.verified-secrets != 4
      uses: actions/github-script@v6
      with:
        script: |
            core.setFailed('Incorrect number of secrets found.')
