name: test-secret-scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Scan test data
      uses: actions/checkout@v3
      with:
        repository: trufflesecurity/test_keys
        path: test_keys
        token: ${{ github.token }}
      uses: ./secret-scan
      with:
        scan-path: test_keys
    - name: Fail if not found
      if: steps.scan.outputs.verified-secrets != 2
      uses: actions/github-script@v6
      with:
        script: |
            core.setFailed('Incorrect number of secrets found.')
